using HomeSuite.Domain.Entities;
using HomeSuite.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace HomeSuite.Infrastructure.Services;

public class UpcomingMealPlanShoppingListSyncService
{
    private const string ShoppingListName = "Mealplanung · nächste 2 Wochen";
    private const string SourceType = "MealPlanUpcoming";

    private readonly HomeSuiteDbContext _dbContext;

    public UpcomingMealPlanShoppingListSyncService(HomeSuiteDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    public async Task SyncAsync(CancellationToken cancellationToken = default)
    {
        var today = DateOnly.FromDateTime(DateTime.UtcNow);
        var endDate = today.AddDays(14);

        var mealPlans = await _dbContext.MealPlans
            .Include(x => x.Recipe)
            .ThenInclude(x => x!.Ingredients)
            .Where(x => !x.IsCompleted && x.Date >= today && x.Date <= endDate)
            .ToListAsync(cancellationToken);

        var aggregatedRequirements = new Dictionary<string, AggregatedRequirement>(StringComparer.OrdinalIgnoreCase);

        foreach (var mealPlan in mealPlans)
        {
            if (mealPlan.Recipe?.Ingredients is null)
            {
                continue;
            }

            var baseServings = mealPlan.Recipe.BaseServings <= 0 ? 1 : mealPlan.Recipe.BaseServings;
            var factor = mealPlan.Servings / (decimal)baseServings;

            foreach (var ingredient in mealPlan.Recipe.Ingredients)
            {
                var normalizedName = ingredient.Name.Trim();
                var normalizedUnit = string.IsNullOrWhiteSpace(ingredient.Unit) ? "Stk" : ingredient.Unit.Trim();

                if (string.IsNullOrWhiteSpace(normalizedName))
                {
                    continue;
                }

                var requiredQuantity = ingredient.Quantity * factor;

                if (requiredQuantity <= 0)
                {
                    continue;
                }

                var key = BuildIngredientKey(normalizedName, normalizedUnit);

                if (aggregatedRequirements.TryGetValue(key, out var existing))
                {
                    existing.RequiredQuantity += requiredQuantity;
                }
                else
                {
                    aggregatedRequirements[key] = new AggregatedRequirement
                    {
                        Name = normalizedName,
                        Unit = normalizedUnit,
                        RequiredQuantity = requiredQuantity
                    };
                }
            }
        }

        var inventoryItems = await _dbContext.InventoryItems.ToListAsync(cancellationToken);
        var catalogItems = await _dbContext.CatalogItems
            .Include(x => x.Prices)
            .ToListAsync(cancellationToken);

        var catalogLookup = catalogItems
            .GroupBy(
                x => BuildIngredientKey(x.Name, x.DefaultUnit),
                StringComparer.OrdinalIgnoreCase)
            .ToDictionary(
                x => x.Key,
                x => x
                    .OrderBy(item => item.Name.Length)
                    .First(),
                StringComparer.OrdinalIgnoreCase);

        var catalogNameLookup = catalogItems
            .GroupBy(
                x => x.Name.Trim().ToLowerInvariant(),
                StringComparer.OrdinalIgnoreCase)
            .ToDictionary(
                x => x.Key,
                x => x
                    .OrderBy(item => item.Name.Length)
                    .First(),
                StringComparer.OrdinalIgnoreCase);

        foreach (var inventoryItem in inventoryItems)
        {
            var key = BuildIngredientKey(inventoryItem.Name, inventoryItem.Unit);

            if (aggregatedRequirements.TryGetValue(key, out var requirement))
            {
                requirement.InventoryQuantity = Math.Max(0, inventoryItem.Quantity);
            }
        }

        var shoppingList = await _dbContext.ShoppingLists
            .Include(x => x.Items)
            .ThenInclude(x => x.PriceOptions)
            .FirstOrDefaultAsync(x => x.Name == ShoppingListName, cancellationToken);

        if (shoppingList is null)
        {
            shoppingList = new ShoppingList
            {
                Name = ShoppingListName,
                CreatedAt = DateTime.UtcNow
            };

            _dbContext.ShoppingLists.Add(shoppingList);
            await _dbContext.SaveChangesAsync(cancellationToken);
        }

        var autoGeneratedItems = shoppingList.Items
            .Where(x => x.SourceType == SourceType)
            .ToDictionary(
                x => BuildIngredientKey(x.Name, x.Unit),
                x => x,
                StringComparer.OrdinalIgnoreCase);

        foreach (var requirement in aggregatedRequirements.Values)
        {
            var key = BuildIngredientKey(requirement.Name, requirement.Unit);
            var inventoryQuantityUsed = Math.Min(requirement.RequiredQuantity, requirement.InventoryQuantity);
            var missingQuantity = Math.Max(0, requirement.RequiredQuantity - inventoryQuantityUsed);

            if (missingQuantity <= 0)
            {
                if (autoGeneratedItems.TryGetValue(key, out var obsoleteExistingItem))
                {
                    _dbContext.ShoppingItems.Remove(obsoleteExistingItem);
                    autoGeneratedItems.Remove(key);
                }

                continue;
            }

            if (autoGeneratedItems.TryGetValue(key, out var shoppingItem))
            {
                shoppingItem.Name = requirement.Name;
                shoppingItem.Unit = requirement.Unit;
                shoppingItem.RequiredQuantity = requirement.RequiredQuantity;
                shoppingItem.InventoryQuantityUsed = inventoryQuantityUsed;
                shoppingItem.Quantity = missingQuantity;
                shoppingItem.PurchasedQuantity = 0;
                shoppingItem.IsChecked = false;
                shoppingItem.SourceType = SourceType;
                ApplyCatalogPricing(
                    shoppingItem,
                    ResolveCatalogItem(requirement.Name, requirement.Unit, catalogLookup, catalogNameLookup));
                autoGeneratedItems.Remove(key);
            }
            else
            {
                var newShoppingItem = new ShoppingItem
                {
                    Name = requirement.Name,
                    Unit = requirement.Unit,
                    RequiredQuantity = requirement.RequiredQuantity,
                    InventoryQuantityUsed = inventoryQuantityUsed,
                    Quantity = missingQuantity,
                    PurchasedQuantity = 0,
                    IsChecked = false,
                    SourceType = SourceType,
                    ShoppingListId = shoppingList.Id
                };

                ApplyCatalogPricing(
                    newShoppingItem,
                    ResolveCatalogItem(requirement.Name, requirement.Unit, catalogLookup, catalogNameLookup));

                _dbContext.ShoppingItems.Add(newShoppingItem);
            }
        }

        foreach (var obsoleteItem in autoGeneratedItems.Values)
        {
            _dbContext.ShoppingItems.Remove(obsoleteItem);
        }

        await _dbContext.SaveChangesAsync(cancellationToken);
    }

    private static string BuildIngredientKey(string name, string unit)
    {
        return $"{name.Trim().ToLowerInvariant()}|{(string.IsNullOrWhiteSpace(unit) ? "Stk" : unit.Trim()).ToLowerInvariant()}";
    }

    private static CatalogItem? ResolveCatalogItem(
        string ingredientName,
        string unit,
        IReadOnlyDictionary<string, CatalogItem> catalogLookup,
        IReadOnlyDictionary<string, CatalogItem> catalogNameLookup)
    {
        var exactKey = BuildIngredientKey(ingredientName, unit);

        if (catalogLookup.TryGetValue(exactKey, out var exactMatch))
        {
            return exactMatch;
        }

        var normalizedName = ingredientName.Trim().ToLowerInvariant();
        return catalogNameLookup.TryGetValue(normalizedName, out var nameMatch)
            ? nameMatch
            : null;
    }

    private static void ApplyCatalogPricing(ShoppingItem shoppingItem, CatalogItem? catalogItem)
    {
        shoppingItem.CatalogItemId = catalogItem?.Id;
        shoppingItem.EstimatedUnitPrice = null;
        shoppingItem.EstimatedTotalPrice = null;

        if (catalogItem is null)
        {
            return;
        }

        var normalizedQuantity = shoppingItem.Quantity > 0 ? shoppingItem.Quantity : 1m;
        var availablePrices = catalogItem.Prices
            .Where(price => price.IsAvailable)
            .Where(price => price.TotalPrice.HasValue || price.UnitPrice.HasValue)
            .OrderBy(price => price.TotalPrice ?? decimal.MaxValue)
            .ThenBy(price => price.UnitPrice ?? decimal.MaxValue)
            .ToList();

        if (availablePrices.Count == 0)
        {
            return;
        }

        foreach (var price in availablePrices)
        {
            var scaledUnitPrice = price.UnitPrice;
            var scaledTotalPrice = price.TotalPrice.HasValue
                ? price.TotalPrice.Value * normalizedQuantity
                : price.UnitPrice.HasValue
                    ? price.UnitPrice.Value * normalizedQuantity
                    : 0m;

            var optionKey = BuildPriceOptionKey(price.StoreName, price.ProductName, price.ProductUrl);
            var existingOption = shoppingItem.PriceOptions.FirstOrDefault(option =>
                string.Equals(BuildPriceOptionKey(option.StoreName, option.ProductName, option.ProductUrl), optionKey, StringComparison.OrdinalIgnoreCase));

            if (existingOption is null)
            {
                shoppingItem.PriceOptions.Add(new ShoppingItemPriceOption
                {
                    StoreName = price.StoreName,
                    ProductName = price.ProductName,
                    UnitPrice = scaledUnitPrice ?? scaledTotalPrice,
                    TotalPrice = scaledTotalPrice,
                    ProductUrl = price.ProductUrl,
                    IsAvailable = price.IsAvailable,
                    CheckedAt = price.CheckedAt
                });
            }
            else
            {
                existingOption.StoreName = price.StoreName;
                existingOption.ProductName = price.ProductName;
                existingOption.UnitPrice = scaledUnitPrice ?? scaledTotalPrice;
                existingOption.TotalPrice = scaledTotalPrice;
                existingOption.ProductUrl = price.ProductUrl;
                existingOption.IsAvailable = price.IsAvailable;
                existingOption.CheckedAt = price.CheckedAt;
            }
        }

        var bestPrice = availablePrices[0];
        shoppingItem.EstimatedUnitPrice = bestPrice.UnitPrice ?? bestPrice.TotalPrice;
        shoppingItem.EstimatedTotalPrice = bestPrice.TotalPrice.HasValue
            ? bestPrice.TotalPrice.Value * normalizedQuantity
            : bestPrice.UnitPrice.HasValue
                ? bestPrice.UnitPrice.Value * normalizedQuantity
                : null;
    }

    private static string BuildPriceOptionKey(string storeName, string productName, string? productUrl)
    {
        var normalizedStore = storeName.Trim().ToLowerInvariant();
        var normalizedProduct = productName.Trim().ToLowerInvariant();
        var normalizedUrl = string.IsNullOrWhiteSpace(productUrl) ? null : productUrl.Trim().ToLowerInvariant();
        return $"{normalizedStore}|{normalizedProduct}|{normalizedUrl}";
    }

    private sealed class AggregatedRequirement
    {
        public string Name { get; set; } = string.Empty;
        public decimal RequiredQuantity { get; set; }
        public decimal InventoryQuantity { get; set; }
        public string Unit { get; set; } = string.Empty;
    }
}
