using HomeSuite.Domain.Entities;
using HomeSuite.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace HomeSuite.Infrastructure.Services;

public class UpcomingMealPlanShoppingListSyncService
{
    private const string ShoppingListName = "Mealplanung · nächste 2 Wochen";
    private const string SourceType = "MealPlanUpcoming";

    private readonly HomeSuiteDbContext _dbContext;

    public UpcomingMealPlanShoppingListSyncService(HomeSuiteDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    public async Task SyncAsync(CancellationToken cancellationToken = default)
    {
        var today = DateOnly.FromDateTime(DateTime.UtcNow);
        var endDate = today.AddDays(14);

        var mealPlans = await _dbContext.MealPlans
            .Include(x => x.Recipe)
            .ThenInclude(x => x!.Ingredients)
            .Where(x => !x.IsCompleted && x.Date >= today && x.Date <= endDate)
            .ToListAsync(cancellationToken);

        var aggregatedRequirements = new Dictionary<string, AggregatedRequirement>(StringComparer.OrdinalIgnoreCase);

        foreach (var mealPlan in mealPlans)
        {
            if (mealPlan.Recipe?.Ingredients is null)
            {
                continue;
            }

            var baseServings = mealPlan.Recipe.BaseServings <= 0 ? 1 : mealPlan.Recipe.BaseServings;
            var factor = mealPlan.Servings / (decimal)baseServings;

            foreach (var ingredient in mealPlan.Recipe.Ingredients)
            {
                var normalizedName = ingredient.Name.Trim();
                var normalizedUnit = string.IsNullOrWhiteSpace(ingredient.Unit) ? "Stk" : ingredient.Unit.Trim();

                if (string.IsNullOrWhiteSpace(normalizedName))
                {
                    continue;
                }

                var requiredQuantity = ingredient.Quantity * factor;

                if (requiredQuantity <= 0)
                {
                    continue;
                }

                var key = BuildIngredientKey(normalizedName, normalizedUnit);

                if (aggregatedRequirements.TryGetValue(key, out var existing))
                {
                    existing.RequiredQuantity += requiredQuantity;
                }
                else
                {
                    aggregatedRequirements[key] = new AggregatedRequirement
                    {
                        Name = normalizedName,
                        Unit = normalizedUnit,
                        RequiredQuantity = requiredQuantity
                    };
                }
            }
        }

        var inventoryItems = await _dbContext.InventoryItems.ToListAsync(cancellationToken);

        foreach (var inventoryItem in inventoryItems)
        {
            var key = BuildIngredientKey(inventoryItem.Name, inventoryItem.Unit);

            if (aggregatedRequirements.TryGetValue(key, out var requirement))
            {
                requirement.InventoryQuantity = Math.Max(0, inventoryItem.Quantity);
            }
        }

        var shoppingList = await _dbContext.ShoppingLists
            .Include(x => x.Items)
            .FirstOrDefaultAsync(x => x.Name == ShoppingListName, cancellationToken);

        if (shoppingList is null)
        {
            shoppingList = new ShoppingList
            {
                Name = ShoppingListName,
                CreatedAt = DateTime.UtcNow
            };

            _dbContext.ShoppingLists.Add(shoppingList);
            await _dbContext.SaveChangesAsync(cancellationToken);
        }

        var autoGeneratedItems = shoppingList.Items
            .Where(x => x.SourceType == SourceType)
            .ToDictionary(
                x => BuildIngredientKey(x.Name, x.Unit),
                x => x,
                StringComparer.OrdinalIgnoreCase);

        foreach (var requirement in aggregatedRequirements.Values)
        {
            var key = BuildIngredientKey(requirement.Name, requirement.Unit);
            var inventoryQuantityUsed = Math.Min(requirement.RequiredQuantity, requirement.InventoryQuantity);
            var missingQuantity = Math.Max(0, requirement.RequiredQuantity - inventoryQuantityUsed);

            if (missingQuantity <= 0)
            {
                if (autoGeneratedItems.TryGetValue(key, out var obsoleteExistingItem))
                {
                    _dbContext.ShoppingItems.Remove(obsoleteExistingItem);
                    autoGeneratedItems.Remove(key);
                }

                continue;
            }

            if (autoGeneratedItems.TryGetValue(key, out var shoppingItem))
            {
                shoppingItem.Name = requirement.Name;
                shoppingItem.Unit = requirement.Unit;
                shoppingItem.RequiredQuantity = requirement.RequiredQuantity;
                shoppingItem.InventoryQuantityUsed = inventoryQuantityUsed;
                shoppingItem.Quantity = missingQuantity;
                shoppingItem.PurchasedQuantity = 0;
                shoppingItem.IsChecked = false;
                shoppingItem.SourceType = SourceType;
                autoGeneratedItems.Remove(key);
            }
            else
            {
                _dbContext.ShoppingItems.Add(new ShoppingItem
                {
                    Name = requirement.Name,
                    Unit = requirement.Unit,
                    RequiredQuantity = requirement.RequiredQuantity,
                    InventoryQuantityUsed = inventoryQuantityUsed,
                    Quantity = missingQuantity,
                    PurchasedQuantity = 0,
                    IsChecked = false,
                    SourceType = SourceType,
                    ShoppingListId = shoppingList.Id
                });
            }
        }

        foreach (var obsoleteItem in autoGeneratedItems.Values)
        {
            _dbContext.ShoppingItems.Remove(obsoleteItem);
        }

        await _dbContext.SaveChangesAsync(cancellationToken);
    }

    private static string BuildIngredientKey(string name, string unit)
    {
        return $"{name.Trim().ToLowerInvariant()}|{(string.IsNullOrWhiteSpace(unit) ? "Stk" : unit.Trim()).ToLowerInvariant()}";
    }

    private sealed class AggregatedRequirement
    {
        public string Name { get; set; } = string.Empty;
        public decimal RequiredQuantity { get; set; }
        public decimal InventoryQuantity { get; set; }
        public string Unit { get; set; } = string.Empty;
    }
}
